### ISSUE TITLE
SwitchConfig, GetConfigReply and SetConfig Classes

### ISSUE THREAD

**Issue by diraol** [kytos/ofx-parser#4]
The message definition for the get_config_reply and set_config messages are the same, both based on the "SwitchConfig" class. The only difference is the ofp_type on the header of the message.

Because of that, on the spec they only implement the "switch_config" (struct).

Would it be better for us to implement the "SwitchConfig" class, and then create a child class for get_config_reply and another on the set_config, both on the respective files (controller2switch/get_config_reply.py and controller2switch/set_config.py)?

Where would be a good place to put the SwitchConfig class? Maybe a "controller2switch/switch_config.py"? Or something on the "foundation" module?

**Comment by andretadeu** [comment]
From my point of view, placing the SwitchConfig in controller2switch/switch_config.py seems to be better.
